Homebrew update for new m1 macs
thinkshout/ts_environment pull request #59
Opened 2023-05-01 16:53 UTC by solbdougherty

Pretty sure this should work for both chipsets

2023-05-01 18:52 UTC, wxactly requested changes

2023-05-01 18:52 UTC, wxactly commented on environment_setup.sh
> +    if [ "$is_intel" == "/opt/homebrew/bin/brew" ] ; then
undefined var - should this be `is_m1`?

2023-05-02 13:59 UTC, solbdougherty commented on environment_setup.sh
> +    if [ "$is_intel" == "/opt/homebrew/bin/brew" ] ; then
@wxactly yep my bad fixed

2023-05-02 22:25 UTC, komejo approved these changes
Looks good!

2023-05-02 22:26 UTC, merged